/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BusinessCardRouteImport } from './routes/business-card'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FindUsRouteImport } from './routes/find-us'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as PartExchangeRouteImport } from './routes/part-exchange'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SellYourCarRouteImport } from './routes/sell-your-car'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StocklistRouteImport } from './routes/stocklist'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as VehicleIdRouteImport } from './routes/vehicle.$id'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedEnquiriesRouteImport } from './routes/admin/_authed/enquiries'
import { Route as AdminAuthedGlobalRouteImport } from './routes/admin/_authed/global'
import { Route as AdminAuthedMediaRouteImport } from './routes/admin/_authed/media'
import { Route as AdminAuthedNavigationRouteImport } from './routes/admin/_authed/navigation'
import { Route as AdminAuthedOrdersRouteImport } from './routes/admin/_authed/orders'
import { Route as AdminAuthedProfileRouteImport } from './routes/admin/_authed/profile'
import { Route as AdminAuthedSettingsRouteImport } from './routes/admin/_authed/settings'
import { Route as AdminAuthedTestimonialsRouteImport } from './routes/admin/_authed/testimonials'
import { Route as AdminAuthedVehiclesIndexRouteImport } from './routes/admin/_authed/vehicles/index'
import { Route as AdminAuthedVehiclesCategoriesRouteImport } from './routes/admin/_authed/vehicles/categories'
import { Route as AdminAuthedVehiclesNewRouteImport } from './routes/admin/_authed/vehicles/new'
import { Route as AdminAuthedVehiclesSoldRouteImport } from './routes/admin/_authed/vehicles/sold'
import { Route as AdminAuthedWebsiteIndexRouteImport } from './routes/admin/_authed/website/index'
import { Route as AdminAuthedWebsiteSlugRouteImport } from './routes/admin/_authed/website/$slug'
import { Route as AdminAuthedVehiclesIdEditRouteImport } from './routes/admin/_authed/vehicles/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCardRoute = BusinessCardRouteImport.update({
  id: '/business-card',
  path: '/business-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FindUsRoute = FindUsRouteImport.update({
  id: '/find-us',
  path: '/find-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const PartExchangeRoute = PartExchangeRouteImport.update({
  id: '/part-exchange',
  path: '/part-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourCarRoute = SellYourCarRouteImport.update({
  id: '/sell-your-car',
  path: '/sell-your-car',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StocklistRoute = StocklistRouteImport.update({
  id: '/stocklist',
  path: '/stocklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleIdRoute = VehicleIdRouteImport.update({
  id: '/vehicle/$id',
  path: '/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedEnquiriesRoute = AdminAuthedEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedGlobalRoute = AdminAuthedGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedMediaRoute = AdminAuthedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedNavigationRoute = AdminAuthedNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedOrdersRoute = AdminAuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProfileRoute = AdminAuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSettingsRoute = AdminAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedTestimonialsRoute = AdminAuthedTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedVehiclesIndexRoute =
  AdminAuthedVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedVehiclesCategoriesRoute =
  AdminAuthedVehiclesCategoriesRouteImport.update({
    id: '/vehicles/categories',
    path: '/vehicles/categories',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedVehiclesNewRoute = AdminAuthedVehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedVehiclesSoldRoute = AdminAuthedVehiclesSoldRouteImport.update({
  id: '/vehicles/sold',
  path: '/vehicles/sold',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedWebsiteIndexRoute = AdminAuthedWebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedWebsiteSlugRoute = AdminAuthedWebsiteSlugRouteImport.update({
  id: '/website/$slug',
  path: '/website/$slug',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedVehiclesIdEditRoute =
  AdminAuthedVehiclesIdEditRouteImport.update({
    id: '/vehicles/$id/edit',
    path: '/vehicles/$id/edit',
    getParentRoute: () => AdminAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/business-card': typeof BusinessCardRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finance': typeof FinanceRoute
  '/find-us': typeof FindUsRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/part-exchange': typeof PartExchangeRoute
  '/reviews': typeof ReviewsRoute
  '/sell-your-car': typeof SellYourCarRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/stocklist': typeof StocklistRoute
  '/valuation': typeof ValuationRoute
  '/warranty': typeof WarrantyRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/admin/enquiries': typeof AdminAuthedEnquiriesRoute
  '/admin/global': typeof AdminAuthedGlobalRoute
  '/admin/media': typeof AdminAuthedMediaRoute
  '/admin/navigation': typeof AdminAuthedNavigationRoute
  '/admin/orders': typeof AdminAuthedOrdersRoute
  '/admin/profile': typeof AdminAuthedProfileRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/testimonials': typeof AdminAuthedTestimonialsRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/vehicles/categories': typeof AdminAuthedVehiclesCategoriesRoute
  '/admin/vehicles/new': typeof AdminAuthedVehiclesNewRoute
  '/admin/vehicles/sold': typeof AdminAuthedVehiclesSoldRoute
  '/admin/website/$slug': typeof AdminAuthedWebsiteSlugRoute
  '/admin/vehicles/': typeof AdminAuthedVehiclesIndexRoute
  '/admin/website/': typeof AdminAuthedWebsiteIndexRoute
  '/admin/vehicles/$id/edit': typeof AdminAuthedVehiclesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/business-card': typeof BusinessCardRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finance': typeof FinanceRoute
  '/find-us': typeof FindUsRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/part-exchange': typeof PartExchangeRoute
  '/reviews': typeof ReviewsRoute
  '/sell-your-car': typeof SellYourCarRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/stocklist': typeof StocklistRoute
  '/valuation': typeof ValuationRoute
  '/warranty': typeof WarrantyRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/admin/enquiries': typeof AdminAuthedEnquiriesRoute
  '/admin/global': typeof AdminAuthedGlobalRoute
  '/admin/media': typeof AdminAuthedMediaRoute
  '/admin/navigation': typeof AdminAuthedNavigationRoute
  '/admin/orders': typeof AdminAuthedOrdersRoute
  '/admin/profile': typeof AdminAuthedProfileRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/testimonials': typeof AdminAuthedTestimonialsRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/vehicles/categories': typeof AdminAuthedVehiclesCategoriesRoute
  '/admin/vehicles/new': typeof AdminAuthedVehiclesNewRoute
  '/admin/vehicles/sold': typeof AdminAuthedVehiclesSoldRoute
  '/admin/website/$slug': typeof AdminAuthedWebsiteSlugRoute
  '/admin/vehicles': typeof AdminAuthedVehiclesIndexRoute
  '/admin/website': typeof AdminAuthedWebsiteIndexRoute
  '/admin/vehicles/$id/edit': typeof AdminAuthedVehiclesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/business-card': typeof BusinessCardRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/finance': typeof FinanceRoute
  '/find-us': typeof FindUsRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/part-exchange': typeof PartExchangeRoute
  '/reviews': typeof ReviewsRoute
  '/sell-your-car': typeof SellYourCarRoute
  '/services': typeof ServicesRoute
  '/stock': typeof StockRoute
  '/stocklist': typeof StocklistRoute
  '/valuation': typeof ValuationRoute
  '/warranty': typeof WarrantyRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/vehicle/$id': typeof VehicleIdRoute
  '/admin/_authed/enquiries': typeof AdminAuthedEnquiriesRoute
  '/admin/_authed/global': typeof AdminAuthedGlobalRoute
  '/admin/_authed/media': typeof AdminAuthedMediaRoute
  '/admin/_authed/navigation': typeof AdminAuthedNavigationRoute
  '/admin/_authed/orders': typeof AdminAuthedOrdersRoute
  '/admin/_authed/profile': typeof AdminAuthedProfileRoute
  '/admin/_authed/settings': typeof AdminAuthedSettingsRoute
  '/admin/_authed/testimonials': typeof AdminAuthedTestimonialsRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/vehicles/categories': typeof AdminAuthedVehiclesCategoriesRoute
  '/admin/_authed/vehicles/new': typeof AdminAuthedVehiclesNewRoute
  '/admin/_authed/vehicles/sold': typeof AdminAuthedVehiclesSoldRoute
  '/admin/_authed/website/$slug': typeof AdminAuthedWebsiteSlugRoute
  '/admin/_authed/vehicles/': typeof AdminAuthedVehiclesIndexRoute
  '/admin/_authed/website/': typeof AdminAuthedWebsiteIndexRoute
  '/admin/_authed/vehicles/$id/edit': typeof AdminAuthedVehiclesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/business-card'
    | '/contact'
    | '/faq'
    | '/finance'
    | '/find-us'
    | '/order-confirmed'
    | '/part-exchange'
    | '/reviews'
    | '/sell-your-car'
    | '/services'
    | '/stock'
    | '/stocklist'
    | '/valuation'
    | '/warranty'
    | '/admin'
    | '/admin/login'
    | '/checkout/$id'
    | '/vehicle/$id'
    | '/admin/enquiries'
    | '/admin/global'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
    | '/admin/vehicles/categories'
    | '/admin/vehicles/new'
    | '/admin/vehicles/sold'
    | '/admin/website/$slug'
    | '/admin/vehicles/'
    | '/admin/website/'
    | '/admin/vehicles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/business-card'
    | '/contact'
    | '/faq'
    | '/finance'
    | '/find-us'
    | '/order-confirmed'
    | '/part-exchange'
    | '/reviews'
    | '/sell-your-car'
    | '/services'
    | '/stock'
    | '/stocklist'
    | '/valuation'
    | '/warranty'
    | '/admin/login'
    | '/checkout/$id'
    | '/vehicle/$id'
    | '/admin/enquiries'
    | '/admin/global'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/orders'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin'
    | '/admin/vehicles/categories'
    | '/admin/vehicles/new'
    | '/admin/vehicles/sold'
    | '/admin/website/$slug'
    | '/admin/vehicles'
    | '/admin/website'
    | '/admin/vehicles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/business-card'
    | '/contact'
    | '/faq'
    | '/finance'
    | '/find-us'
    | '/order-confirmed'
    | '/part-exchange'
    | '/reviews'
    | '/sell-your-car'
    | '/services'
    | '/stock'
    | '/stocklist'
    | '/valuation'
    | '/warranty'
    | '/admin/_authed'
    | '/admin/login'
    | '/checkout/$id'
    | '/vehicle/$id'
    | '/admin/_authed/enquiries'
    | '/admin/_authed/global'
    | '/admin/_authed/media'
    | '/admin/_authed/navigation'
    | '/admin/_authed/orders'
    | '/admin/_authed/profile'
    | '/admin/_authed/settings'
    | '/admin/_authed/testimonials'
    | '/admin/_authed/'
    | '/admin/_authed/vehicles/categories'
    | '/admin/_authed/vehicles/new'
    | '/admin/_authed/vehicles/sold'
    | '/admin/_authed/website/$slug'
    | '/admin/_authed/vehicles/'
    | '/admin/_authed/website/'
    | '/admin/_authed/vehicles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  BusinessCardRoute: typeof BusinessCardRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FinanceRoute: typeof FinanceRoute
  FindUsRoute: typeof FindUsRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PartExchangeRoute: typeof PartExchangeRoute
  ReviewsRoute: typeof ReviewsRoute
  SellYourCarRoute: typeof SellYourCarRoute
  ServicesRoute: typeof ServicesRoute
  StockRoute: typeof StockRoute
  StocklistRoute: typeof StocklistRoute
  ValuationRoute: typeof ValuationRoute
  WarrantyRoute: typeof WarrantyRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  VehicleIdRoute: typeof VehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-card': {
      id: '/business-card'
      path: '/business-card'
      fullPath: '/business-card'
      preLoaderRoute: typeof BusinessCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-us': {
      id: '/find-us'
      path: '/find-us'
      fullPath: '/find-us'
      preLoaderRoute: typeof FindUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-exchange': {
      id: '/part-exchange'
      path: '/part-exchange'
      fullPath: '/part-exchange'
      preLoaderRoute: typeof PartExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-car': {
      id: '/sell-your-car'
      path: '/sell-your-car'
      fullPath: '/sell-your-car'
      preLoaderRoute: typeof SellYourCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocklist': {
      id: '/stocklist'
      path: '/stocklist'
      fullPath: '/stocklist'
      preLoaderRoute: typeof StocklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$id': {
      id: '/vehicle/$id'
      path: '/vehicle/$id'
      fullPath: '/vehicle/$id'
      preLoaderRoute: typeof VehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/enquiries': {
      id: '/admin/_authed/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminAuthedEnquiriesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/global': {
      id: '/admin/_authed/global'
      path: '/global'
      fullPath: '/admin/global'
      preLoaderRoute: typeof AdminAuthedGlobalRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/media': {
      id: '/admin/_authed/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAuthedMediaRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/navigation': {
      id: '/admin/_authed/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminAuthedNavigationRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/orders': {
      id: '/admin/_authed/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAuthedOrdersRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/profile': {
      id: '/admin/_authed/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAuthedProfileRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/settings': {
      id: '/admin/_authed/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthedSettingsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/testimonials': {
      id: '/admin/_authed/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminAuthedTestimonialsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/vehicles/': {
      id: '/admin/_authed/vehicles/'
      path: '/vehicles'
      fullPath: '/admin/vehicles/'
      preLoaderRoute: typeof AdminAuthedVehiclesIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/vehicles/categories': {
      id: '/admin/_authed/vehicles/categories'
      path: '/vehicles/categories'
      fullPath: '/admin/vehicles/categories'
      preLoaderRoute: typeof AdminAuthedVehiclesCategoriesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/vehicles/new': {
      id: '/admin/_authed/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/admin/vehicles/new'
      preLoaderRoute: typeof AdminAuthedVehiclesNewRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/vehicles/sold': {
      id: '/admin/_authed/vehicles/sold'
      path: '/vehicles/sold'
      fullPath: '/admin/vehicles/sold'
      preLoaderRoute: typeof AdminAuthedVehiclesSoldRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/website/': {
      id: '/admin/_authed/website/'
      path: '/website'
      fullPath: '/admin/website/'
      preLoaderRoute: typeof AdminAuthedWebsiteIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/website/$slug': {
      id: '/admin/_authed/website/$slug'
      path: '/website/$slug'
      fullPath: '/admin/website/$slug'
      preLoaderRoute: typeof AdminAuthedWebsiteSlugRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/vehicles/$id/edit': {
      id: '/admin/_authed/vehicles/$id/edit'
      path: '/vehicles/$id/edit'
      fullPath: '/admin/vehicles/$id/edit'
      preLoaderRoute: typeof AdminAuthedVehiclesIdEditRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedEnquiriesRoute: typeof AdminAuthedEnquiriesRoute
  AdminAuthedGlobalRoute: typeof AdminAuthedGlobalRoute
  AdminAuthedMediaRoute: typeof AdminAuthedMediaRoute
  AdminAuthedNavigationRoute: typeof AdminAuthedNavigationRoute
  AdminAuthedOrdersRoute: typeof AdminAuthedOrdersRoute
  AdminAuthedProfileRoute: typeof AdminAuthedProfileRoute
  AdminAuthedSettingsRoute: typeof AdminAuthedSettingsRoute
  AdminAuthedTestimonialsRoute: typeof AdminAuthedTestimonialsRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedVehiclesCategoriesRoute: typeof AdminAuthedVehiclesCategoriesRoute
  AdminAuthedVehiclesNewRoute: typeof AdminAuthedVehiclesNewRoute
  AdminAuthedVehiclesSoldRoute: typeof AdminAuthedVehiclesSoldRoute
  AdminAuthedWebsiteSlugRoute: typeof AdminAuthedWebsiteSlugRoute
  AdminAuthedVehiclesIndexRoute: typeof AdminAuthedVehiclesIndexRoute
  AdminAuthedWebsiteIndexRoute: typeof AdminAuthedWebsiteIndexRoute
  AdminAuthedVehiclesIdEditRoute: typeof AdminAuthedVehiclesIdEditRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedEnquiriesRoute: AdminAuthedEnquiriesRoute,
  AdminAuthedGlobalRoute: AdminAuthedGlobalRoute,
  AdminAuthedMediaRoute: AdminAuthedMediaRoute,
  AdminAuthedNavigationRoute: AdminAuthedNavigationRoute,
  AdminAuthedOrdersRoute: AdminAuthedOrdersRoute,
  AdminAuthedProfileRoute: AdminAuthedProfileRoute,
  AdminAuthedSettingsRoute: AdminAuthedSettingsRoute,
  AdminAuthedTestimonialsRoute: AdminAuthedTestimonialsRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedVehiclesCategoriesRoute: AdminAuthedVehiclesCategoriesRoute,
  AdminAuthedVehiclesNewRoute: AdminAuthedVehiclesNewRoute,
  AdminAuthedVehiclesSoldRoute: AdminAuthedVehiclesSoldRoute,
  AdminAuthedWebsiteSlugRoute: AdminAuthedWebsiteSlugRoute,
  AdminAuthedVehiclesIndexRoute: AdminAuthedVehiclesIndexRoute,
  AdminAuthedWebsiteIndexRoute: AdminAuthedWebsiteIndexRoute,
  AdminAuthedVehiclesIdEditRoute: AdminAuthedVehiclesIdEditRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  BusinessCardRoute: BusinessCardRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FinanceRoute: FinanceRoute,
  FindUsRoute: FindUsRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PartExchangeRoute: PartExchangeRoute,
  ReviewsRoute: ReviewsRoute,
  SellYourCarRoute: SellYourCarRoute,
  ServicesRoute: ServicesRoute,
  StockRoute: StockRoute,
  StocklistRoute: StocklistRoute,
  ValuationRoute: ValuationRoute,
  WarrantyRoute: WarrantyRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  VehicleIdRoute: VehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
